src/Entity/Doctor.php
<?php

namespace App\Entity;
use App\Entity\Users;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;



/**
 * @Vich\Uploadable()
 * @ORM\Entity(repositoryClass="App\Repository\DoctorRepository")
 * 
 */
class Doctor extends Users 
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Regex("#^[a-zA-Z]{3,120}.*[\s\.]*$#", message="Elle ne doit pas contenir de caractères spéciaux ou de chiffres et doit avoir minimum 2 caractères")
     * 
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @Assert\Regex("#^[a-zA-Z]{3,120}.*[\s\.]*$#", message="Ce champ ne doit pas contenir de caractères spéciaux ou de chiffres")
     *@ORM\Column(type="string", length=255)
     */
    private $LastName;

    /**
     * @Assert\Regex("#^\+(221)-[0-9]{2}-[0-9]{3}-[0-9]{2}-[0-9]{2}$#", message="Votre numéro doit suivre ce format : +221-(77/76/70)-000-00-00")
     * @ORM\Column(type="string", length=255)
     */
    private $numberPhone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pictureProfil;
   
    /**
     * @var File|null
     * @Vich\UploadableField(mapping="pictureProfile", fileNameProperty="pictureProfil")
     */
    private $imageFile;
    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $tarifMin;

    /**
     * @Assert\GreaterThan(propertyPath="tarifMin", message="Le tarif maximum doit être supérieur au tarif minimum")
     * @ORM\Column(type="float", nullable=true)
     */
    private $tarifMax;

    /**
    *@Assert\Length(
     *      min = 15,
     *      minMessage = "Votre présentation doit faire au moins {{ limit }} mots",
     * )
     * @ORM\Column(type="text", nullable=true)
     */
    private $presentation;

    /**
     * @Gedmo\Slug(fields={"firstName", "LastName"})
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="boolean", options={"default":true})
     */
    private $enable=true;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Profession", inversedBy="doctor")
     * @ORM\JoinColumn(nullable=false)
     */
    private $profession;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Expertise", inversedBy="doctors")
     */
    private $expertise;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Language", inversedBy="doctors")
     */
    private $language;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Location", inversedBy="doctor", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $location;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\MeansPayment", inversedBy="doctors")
     */
    private $meansPayment;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\PraticalInfos", inversedBy="doctors")
     */
    private $praticalInfos;


    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Refund", inversedBy="doctors")
     */
    private $refund;

    /**
     * @var \DateTime $updatedAt
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;
    /**
     * @var \DateTime $createdAt
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\DoctorSocialNetworks", mappedBy="doctor", orphanRemoval=true)
     */
    private $doctorSocialNetworks;

    /**
     * @ORM\ManyToMany(targetEntity=Appointment::class, inversedBy="doctors")
     */
    private $appointement;

    public function __construct()
    {
        parent::__construct();
        $this->expertise = new ArrayCollection();
        $this->language = new ArrayCollection();
        $this->meansPayment = new ArrayCollection();
        $this->praticalInfos = new ArrayCollection();
        $this->refund = new ArrayCollection();
        $this->doctorSocialNetworks = new ArrayCollection();
        $this->appointement = new ArrayCollection();
    }


    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getNumberPhone(): ?string
    {
        return $this->numberPhone;
    }

    public function setNumberPhone(string $numberPhone): self
    {
        $this->numberPhone = $numberPhone;

        return $this;
    }

    public function getPictureProfil(): ?string
    {
        return $this->pictureProfil;
    }

    public function setPictureProfil(?string $pictureProfil): self
    {
        $this->pictureProfil = $pictureProfil;

        return $this;
    }

    public function getTarifMin(): ?float
    {
        return $this->tarifMin;
    }

    public function setTarifMin(float $tarifMin): self
    {
        $this->tarifMin = $tarifMin;

        return $this;
    }

    public function getTarifMax(): ?float
    {
        return $this->tarifMax;
    }

    public function setTarifMax(float $tarifMax): self
    {
        $this->tarifMax = $tarifMax;

        return $this;
    }

    public function getPresentation(): ?string
    {
        return $this->presentation;
    }

    public function getFullTarif(): ?string
    {
        $this->tarifMax=number_format($this->tarifMax , 0 ," "," ");
        $this->tarifMin=number_format($this->tarifMin , 0 ," "," ");
       return "{$this->tarifMin} CFA - {$this->tarifMax} CFA";
    }

    public function setPresentation(string $presentation): self
    {
        $this->presentation = $presentation;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getEnable(): ?bool
    {
        return $this->enable;
    }

    public function setEnable(bool $enable): self
    {
        $this->enable = $enable;

        return $this;
    }

    public function getProfession(): ?Profession
    {
        return $this->profession;
    }

    public function setProfession(?Profession $profession): self
    {
        $this->profession = $profession;

        return $this;
    }

    /**
     * @return Collection|Expertise[]
     */
    public function getExpertise(): Collection
    {
        return $this->expertise;
    }

    public function addExpertise(Expertise $expertise): self
    {
        if (!$this->expertise->contains($expertise)) {
            $this->expertise[] = $expertise;
        }

        return $this;
    }

    public function removeExpertise(Expertise $expertise): self
    {
        if ($this->expertise->contains($expertise)) {
            $this->expertise->removeElement($expertise);
        }

        return $this;
    }

    /**
     * @return Collection|Language[]
     */
    public function getLanguage(): Collection
    {
        return $this->language;
    }

    public function addLanguage(Language $language): self
    {
        if (!$this->language->contains($language)) {
            $this->language[] = $language;
        }

        return $this;
    }

    public function removeLanguage(Language $language): self
    {
        if ($this->language->contains($language)) {
            $this->language->removeElement($language);
        }

        return $this;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(Location $location): self
    {
        $this->location = $location;

        return $this;
    }

    /**
     * @return Collection|MeansPayment[]
     */
    public function getMeansPayment(): Collection
    {
        return $this->meansPayment;
    }

    public function addMeansPayment(MeansPayment $meansPayment): self
    {
        if (!$this->meansPayment->contains($meansPayment)) {
            $this->meansPayment[] = $meansPayment;
        }

        return $this;
    }

    public function removeMeansPayment(MeansPayment $meansPayment): self
    {
        if ($this->meansPayment->contains($meansPayment)) {
            $this->meansPayment->removeElement($meansPayment);
        }

        return $this;
    }

    /**
     * @return Collection|PraticalInfos[]
     */
    public function getPraticalInfos(): Collection
    {
        return $this->praticalInfos;
    }

    public function addPraticalInfo(PraticalInfos $praticalInfo): self
    {
        if (!$this->praticalInfos->contains($praticalInfo)) {
            $this->praticalInfos[] = $praticalInfo;
        }

        return $this;
    }

    public function removePraticalInfo(PraticalInfos $praticalInfo): self
    {
        if ($this->praticalInfos->contains($praticalInfo)) {
            $this->praticalInfos->removeElement($praticalInfo);
        }

        return $this;
    }

    /**
     * @return Collection|Refund[]
     */
    public function getRefund(): Collection
    {
        return $this->refund;
    }

    public function addRefund(Refund $refund): self
    {
        if (!$this->refund->contains($refund)) {
            $this->refund[] = $refund;
        }

        return $this;
    }

    public function removeRefund(Refund $refund): self
    {
        if ($this->refund->contains($refund)) {

templates/show_account/main_account_show.html.twig
{% extends "appMain.html.twig" %}
{% block body %}
{% include "includeApp/_navigation.html.twig" %}
{% block style %}
  
{% endblock style %}
<div class="container-profile">
    <header style="background-image: url('{% block header_picture %}{% endblock %}');">
    </header>
      <main>
        <div class="row">
          <div class="left col-lg-4">
            <div class="photo-left">
              {% block picture %}
              {% endblock %}
            </div>
            {% block entityName %}
            {% endblock entityName %}
            <div class="stats row">
              <div class="stat col-xs-4">
                {% block numberPhone %}
                {% endblock numberPhone %}
              </div>
            </div>
            <div class="social">
              {% block linksSocial %}
              {% endblock %}
  
   
            </div>
          </div>
          <div class="right col-lg-8">
            <div class="tab-profiles">
              {% block input %}   
              {% endblock %}         
              <ul>
                  {% block liName %}
                  {% endblock %}
               </ul>

              <div class="{% block slider %}slider{% endblock slider %}"><div class="indicator"></div></div>
              <div class="content">
                  {% block content %}
                  {% endblock %}
              
            </div>          
          </div>
      </main>
    </div>
{% include "includeApp/_footer.html.twig" %}

{% endblock body %}

templates/show_account/show_account_doctor.html.twig
{% extends "show_account/main_account_show.html.twig" %}
{% block header_picture %}{{asset('bower_components/images/doctor-header.jpg') }}{% endblock %}
              {% block picture %}
              {% if doctor.pictureProfil %}             
              {% else %}
              <img class="photo" src="{{asset('bower_components/images/notImageProfile.png') }}" 
               alt="Profile image not available">
              {% endif %}
              {% endblock %}
            {% block entityName %}
            <h4 class="name">{{doctor.fullName}}</h4>
            <p class="info">{{doctor.profession}}</p>
            {% endblock entityName %}
                {% block numberPhone %}
                <p class="number-stat">{{doctor.numberPhone|replace({'-':' ' }) }} </p>  
                {% endblock numberPhone %}
                {% block expertiseInfo %}<span class="info-titre">Domaines d'Expertise</span>          
                <p class="desc">{% for expertise in doctor.expertise %}<span class="badge badge-primary">{{expertise.expertiseName}} </span> {% endfor %}</p>
                <div class="social">{% endblock %}
              {% if doctor.doctorSocialNetworks is defined %}
              {% block linksSocial %}
              
              {% for socialLinks in doctor.doctorSocialNetworks %}
              {% if socialLinks.socialNetworks.socialName|lower == "facebook" %}
             <a href="{{socialLinks}}"><i class="fa fa-facebook-square" aria-hidden="true"></i></a> 
              {% endif %}
              {% if socialLinks.socialNetworks.socialName|lower == "twitter" %}
             <a href="{{socialLinks}}"> <i class="fa fa-twitter-square" aria-hidden="true"></i></a> 
              {% endif %}
              {% if socialLinks.socialNetworks.socialName|lower == "linkedin" %}
              <a href="{{socialLinks}}"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a> 
              {% endif %}
              {% if socialLinks.socialNetworks.socialName|lower == "google+" %}
            <a href="{{socialLinks}}">  <i class="fa fa-google-square" aria-hidden="true"></i></a> 
              {% endif %}
                
              {% endfor %}
              {% endblock %}
              {% else %}
              {% endif %}
                
              {% block input %}
              <input type="radio" id="tab-profile1" name="tab-profile-control" checked>
              <input type="radio" id="tab-profile2" name="tab-profile-control">
              <input type="radio" id="tab-profile3" name="tab-profile-control">    
              {% endblock %}         
                  {% block liName %}
                  <li title="Presentation"><label for="tab-profile1" role="button"><i class="fa fa-book"></i><br><span>Presentation</span></label></li>
                  <li title="Informations"><label for="tab-profile2" role="button"><i class="fa fa-info-circle"></i> <br><span>Informations</span></label></li>
                  <li title="Carte"><label for="tab-profile3" role="button"> <i class="fa fa-map"></i> <br><span>Carte</span></label></li> 
                  {% endblock %}
                  {% block content %}
                  <section>
                      {{doctor.presentation}}
                    </section>
                        <section>
                           <p> <span class="info-titre">Tarifs</span> : {{doctor.fullTarif}}</p>
                          <p>  <span class="info-titre">Langue Parlées</span>: {% for langue in doctor.language %} {{langue}} {% endfor %}</p>
                          <p> <span class="info-titre">Paiement accèptés </span>: {% for means in doctor.meansPayment %} {{means}} {% endfor %}</p>
                          <p> <span class="info-titre">Moyens d'accès</span> :  {% for info in doctor.praticalInfos %} {{info}} {% endfor %}</p>
                          <p> <span class="info-titre">Remboursement(s) accèpté(s)</span> : {% for refund in doctor.refund %} {{refund}} {% endfor %}</p>
                          </section>
                        <section>
                          <div id="map" data-lat="{{doctor.location.latitude}}" data-lon="{{doctor.location.longitude}}"></div>
                          </section>
                  {% endblock %}

templates/show_account/show_account_laboratory.html.twig
{% extends "show_account/main_account_show.html.twig" %}
{% block style %}
<style>
  .tab-profiles .slider {
  position: relative;
  width: 50%;
  -webkit-transition: all 0.33s cubic-bezier(0.38, 0.8, 0.32, 1.07);
  transition: all 0.33s cubic-bezier(0.38, 0.8, 0.32, 1.07);
}
</style>

{% endblock style %}
{% block header_picture %}{{asset('bower_components/images/laboratory-header.jpg') }}{% endblock %}
              {% block picture %}
              {% if laboratory.imageName %}             
              {% else %}
              <img class="photo" src="{{asset('bower_components/images/notImageProfile.png') }}" 
               alt="Profile image not available">
              {% endif %}
              {% endblock %}
            {% block entityName %}
            <h4 class="name">{{laboratory.nameLaboratory}}</h4>
            {% endblock entityName %}
                {% block numberPhone %}
                <p class="number-stat">{{laboratory.numberPhone|replace({'-':' ' }) }} </p>  
                {% endblock numberPhone %}
              {% block linksSocial %}

              {% endblock %}
              {% block input %}
              <input type="radio" id="tab-profile1" name="tab-profile-control" checked>
              {% endblock %}         
                  {% block liName %}
                  <li title="Informations"><label for="tab-profile2" role="button"><i class="fa fa-map"></i> <br> <span>Carte et Informations</span></label></li>
                  {% endblock %}
                  {% block slider %}slider3{% endblock slider %}
                  {% block content %}
                        <section>
                          <p> <span class="info-titre">les catégories de laboratoires</span>: {% for category in laboratory.categoryLaboratory %} <span class="badge badge-primary">{{category}}</span>  {% endfor %}</p>
                          <div id="map"></div>                        
                          <p>
                            {% if laboratory.laboratorySocialNetworks is defined %}
                            {% else %}
                            {% for socialLinks in laboratory.laboratorySocialNetworks %}
                            {% if socialLinks.socialNetworks.socialName|lower == "facebook" %}
                           <a href="{{socialLinks}}"><i class="fa fa-facebook-square" aria-hidden="true"></i></a> 
                            {% endif %}
                            {% if socialLinks.socialNetworks.socialName|lower == "twitter" %}
                           <a href="{{socialLinks}}"> <i class="fa fa-twitter-square" aria-hidden="true"></i></a> 
                            {% endif %}
                            {% if socialLinks.socialNetworks.socialName|lower == "linkedin" %}
                            <a href="{{socialLinks}}"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a> 
                            {% endif %}
                            {% if socialLinks.socialNetworks.socialName|lower == "google+" %}
                          <a href="{{socialLinks}}">  <i class="fa fa-google-square" aria-hidden="true"></i></a> 
                            {% endif %}
                              
                            {% endfor %}
                            {% endif %}
                          </p>
                          </section>
                  {% endblock %}

templates/show_account/show_account_pharmacy.html.twig
{% extends "show_account/main_account_show.html.twig" %}
{% block style %}
<style>
  .tab-profiles .slider {
  position: relative;
  width: 50%;
  -webkit-transition: all 0.33s cubic-bezier(0.38, 0.8, 0.32, 1.07);
  transition: all 0.33s cubic-bezier(0.38, 0.8, 0.32, 1.07);
}
</style>

{% endblock style %}
{% block header_picture %}{{asset('bower_components/images/pharmacy-header.jpg') }}{% endblock %}
              {% block picture %}
              {% if pharmacy.picture %}             
              {% else %}
              <img class="photo" src="{{asset('bower_components/images/notImageProfile.png') }}" 
               alt="Profile image not available">
              {% endif %}
              {% endblock %}
            {% block entityName %}
            <h4 class="name">{{pharmacy.pharmacyName}}</h4>
            {% endblock entityName %}
                {% block numberPhone %}
                <p class="number-stat">{{pharmacy.phoneNumber|replace({'-':' ' }) }} </p>  
                {% endblock numberPhone %}
              {% block linksSocial %}

              {% endblock %}
              {% block input %}
              <input type="radio" id="tab-profile1" name="tab-profile-control" checked>
              <input type="radio" id="tab-profile2" name="tab-profile-control">
              {% endblock %}         
                  {% block liName %}
                  <li title="Informations"><label for="tab-profile1" role="button"><i class="fa fa-info-circle"></i> <br> <span>Informations</span></label></li>
                  <li title="Informations"><label for="tab-profile2" role="button"><i class="fa fa-map"></i> <br> <span>Carte</span></label></li>
                  {% endblock %}
                  {% block slider %}slider2{% endblock slider %}
                  {% block content %}
                        <section>
                          <p> <span class="info-titre">Paiement accèptés </span>: {% for means in pharmacy.meansPayment %} {{means}} {% endfor %}</p>
                          <p>
                            {% if pharmacy.pharmacySocialNetworks is defined %}
                            {% else %}
                            {% for socialLinks in pharmacy.pharmacySocialNetworks %}
                            {% if socialLinks.socialNetworks.socialName|lower == "facebook" %}
                           <a href="{{socialLinks}}"><i class="fa fa-facebook-square" aria-hidden="true"></i></a> 
                            {% endif %}
                            {% if socialLinks.socialNetworks.socialName|lower == "twitter" %}
                           <a href="{{socialLinks}}"> <i class="fa fa-twitter-square" aria-hidden="true"></i></a> 
                            {% endif %}
                            {% if socialLinks.socialNetworks.socialName|lower == "linkedin" %}
                            <a href="{{socialLinks}}"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a> 
                            {% endif %}
                            {% if socialLinks.socialNetworks.socialName|lower == "google+" %}
                          <a href="{{socialLinks}}">  <i class="fa fa-google-square" aria-hidden="true"></i></a> 
                            {% endif %}
                              
                            {% endfor %}
                            {% endif %}
                          </p>
                          </section>
                        <section>
                          <div id="map"></div>
                          </section>
                  {% endblock %}